language: node_js
node_js:
  - "0.12"
  - "0.10"
  - "0.8"
  - "iojs"
before_install:
  - "npm install -g npm@2.1.18"
matrix:
  fast_finish: true
  allow_failures:
    - node_js: "0.8"
    - node_js: "iojs"
